{
    "name":"墨客APT源",
    "icon":"https://apt.cydia.love/CydiaIcon.png",
    "description":"欢迎使用墨客APT会员系统",
    "authentication_banner":{
        "message":"欢迎使用墨客APT会员系统",
        "button":"登录"
    }
}